### ISSUE TITLE
Adds double meet prefix for new meets

### ISSUE THREAD

**Issue by corebots** [pabmartine/gmeet#1]
Hi and thank you for this extension. Whenever try to add a new meeting, the link upon clicking on the item from the menu doesn't work, the url is double:
![image](https://github.com/pabmartine/gmeet/assets/12252430/e14eb5f0-3e25-4eb3-bd14-c1615678fcd1)

**Comment by pabmartine** [comment]
Hi, that’s because you should enter only the code (xxx-yyyy-zzz) not the
complete url.

I will check it because that should be validated.

thanks by your comment 

Pablo.

**Comment by corebots** [comment]
It's happening in both cases for me. First I've added the full url and got a message that it should be the xxx-yyyy-zzz code only. Now when I'm adding the xxx-yyyy-zzz code only, I'm still getting the double url...

**Comment by pabmartine** [comment]
I have checked the code and indeed the url was being duplicated.
It has been corrected and a new version has been uploaded. It will be available soon once it is approved.
Thanks again for the warning.
