### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by DasJott** [pabmartine/gmeet#2]
Would be nice to keep on using this extension.

**Comment by DasJott** [comment]
Hey, thank you for the new version, working on Gnome 46!

I noticed that all of my previous settings were gone and the "add" button has no function :/
Just wanted to let you know :)

**Comment by pabmartine** [comment]
Thanks for the comment,
I updated the extension yesterday evening after upgrading my laptop, but I
didn't really test it.
I will try to fix the problems as soon as possible.

**Comment by pabmartine** [comment]
I have just updated the extension, it will be available once it is
approved. I've fixed the Add button problem and also moved the
bookmarks.json file to /home/.gmeet so it doesn't get overwritten between
updates.
You will need to merge it with your current file which will be in the path
***@***.***

**Comment by DasJott** [comment]
Works perfectly again for me!

Thank you very much for your good work :)
